# Autoformer model-specific hyperparameters
model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]

  n_heads:
    type: categorical
    choices: [4, 8]

  e_layers:
    type: int
    min: 1
    max: 3

  d_layers:
    type: int
    min: 1
    max: 3

  d_ff:
    type: categorical
    choices: [256, 512, 1024]

  moving_avg:
    type: categorical
    choices: [7, 13, 25]

  factor:
    type: int
    min: 1
    max: 5

  activation:
    type: categorical
    choices: ['gelu', 'relu']
