# iTransformer model-specific hyperparameters
model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]

  n_heads:
    type: categorical
    choices: [4, 8]

  e_layers:
    type: int
    min: 1
    max: 4

  d_ff:
    type: categorical
    choices: [128, 256, 512, 1024]

  factor:
    type: int
    min: 1
    max: 3

  embed:
    type: categorical
    choices: ['fixed', 'timeF']

  activation:
    type: categorical
    choices: ['relu', 'gelu']
