# MICN model-specific hyperparameters
model_params:
  d_model:
    type: categorical
    choices: [64, 256, 512, 1024]

  d_layers:
    type: int
    min: 1
    max: 3

  n_heads:
    type: categorical
    choices: [4, 8]

  conv_kernel:
    type: categorical
    choices: [[8, 12], [12, 16], [16, 20]]

  embed:
    type: categorical
    choices: ['fixed', 'timeF']
