# Pyraformer model-specific hyperparameters
model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]

  e_layers:
    type: int
    min: 1
    max: 3

  window_size:
    type: categorical
    choices: [[2, 2], [4, 4], [8, 4]]

  inner_size:
    type: int
    min: 3
    max: 7
