# SCINet model-specific hyperparameters
model_params:
  hid_size:
    type: categorical
    choices: [0.5, 1.0, 2.0, 4.0]

  num_levels:
    type: int
    min: 1
    max: 3

  num_decoder_layer:
    type: int
    min: 1
    max: 3

  concat_len:
    type: int
    min: 0
    max: 0

  groups:
    type: int
    min: 1
    max: 3

  kernel:
    type: int
    min: 3
    max: 7

  positionalE:
    type: categorical
    choices: [true, false]

  modified:
    type: categorical
    choices: [true, false]

  RIN:
    type: categorical
    choices: [true, false]
