# TiDE model-specific hyperparameters
model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]

  d_ff:
    type: categorical
    choices: [256, 512, 1024]

  e_layers:
    type: int
    min: 1
    max: 3

  d_layers:
    type: int
    min: 1
    max: 3

  feature_encode_dim:
    type: int
    min: 1
    max: 3
